const mockData = [
  {
    id: "1",
    name: "Sultanat",
    menu: "Biryani",
    rating: 3,
    price: "Rs.400",
    image: "8B8YLOo.jpg",
  },
  {
    id: "2",
    name: "Food Time",
    menu: "Fries",
    rating: 5,
    price: "Rs.200",
    image: "OHHctnf.jpg",
  },
  {
    id: "3",
    name: "SMA Food",
    menu: "Fast Food",
    rating: 2,
    price: "Rs.500",
    image: "3ZTwCfz.png",
  },
  {
    id: "4",
    name: "Golden Spoon",
    menu: "Chargha",
    rating: 4,
    price: "Rs.1000",
    image: "dyoOLCO.png",
  },
  {
    id: "5",
    name: "Silver Spoon",
    menu: "Chargha",
    rating: 1,
    price: "Rs.1000",
    image: "wOEuXuV.jpg",
  },
  {
    id: "6",
    name: "Silver Spoon",
    menu: "Chargha",
    rating: 5,
    price: "Rs.1000",
    image: "wOEuXuV.jpg",
  },
  {
    id: "7",
    name: "Silver Spoon",
    menu: "Chargha",
    rating: 4,
    price: "Rs.1000",
    image: "wOEuXuV.jpg",
  },
  {
    id: "8",
    name: "Silver Spoon",
    menu: "Chargha",
    rating: 4,
    price: "Rs.1000",
    image: "wOEuXuV.jpg",
  },
];
export default mockData;
